<a href="https://colab.research.google.com/github/tmdgus2444-cloud/GOGOOMA/blob/main/0928%20isan_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

A = {1, 2, 3}
B = {1, 2, 3}

R = {(1,2), (2,3), (3,2), (3,4)}

print("관계 R:", R)


A_list = sorted(A)
B_list = sorted(B)

relation_matrix = np.zeros((len(A_list), len(B_list)), dtype=int)

for i,a in enumerate(A_list):
    for j, b in enumerate(B_list):
        if (a,b) in R:
            relation_matrix[i, j] = 1

print("관계 행렬 (rows: A, columns: B):")
print(relation_matrix)

C = {'x', 'y'}
S = {(2, 'x'), (3, 'y'), (4, 'x')}

composed_relation = set()

for (a, b1) in R:
    for (b2, c) in S:
        if b1 == b2:
            composed_relation.add((a, c))

print("\n합성 관계 R.S:", composed_relation)

관계 R: {(2, 3), (3, 2), (1, 2), (3, 4)}
관계 행렬 (rows: A, columns: B):
[[0 1 0]
 [0 0 1]
 [0 1 0]]

합성 관계 R.S: {(2, 'y'), (3, 'x'), (1, 'x')}
